_wandb:
    value:
        cli_version: 0.24.2
        e:
            420ajz3j74kduf7efnakot8o49klaq1l:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "4294967296"
                codePath: student/ablation_studies/tuning_learning_rate.py
                codePathLocal: tuning_learning_rate.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "789464571904"
                email: nd3032@nyu.edu
                executable: /Users/nilarnabdebnath/Documents/course_work/sem2/llm_reasoners/assignment1/nyu-llm-reasoners-a1/.venv/bin/python
                git:
                    commit: 0f0ff2fcd794b1948b2e41a570032dc030e8a8bc
                    remote: https://github.com/nilarnab/nyu-llm-reasoners-a1.git
                host: Nilarnabs-MacBook-Air.local
                memory:
                    total: "25769803776"
                os: macOS-15.7.3-arm64-arm-64bit-Mach-O
                program: /Users/nilarnabdebnath/Documents/course_work/sem2/llm_reasoners/assignment1/nyu-llm-reasoners-a1/student/ablation_studies/tuning_learning_rate.py
                python: CPython 3.13.7
                root: /Users/nilarnabdebnath/Documents/course_work/sem2/llm_reasoners/assignment1/nyu-llm-reasoners-a1/student/ablation_studies
                startedAt: "2026-02-11T23:53:11.702362Z"
                writerId: 420ajz3j74kduf7efnakot8o49klaq1l
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 61
            "4": 3.13.7
            "5": 0.24.2
            "12": 0.24.2
            "13": darwin-arm64
batch_size:
    value: 256
epochs:
    value: 10000
max_learning_rate:
    value: 0.01
min_learning_rate:
    value: 0.001
model:
    value: transformer
