_wandb:
    value:
        cli_version: 0.24.2
        e:
            fg9r5h7jq7ip5ewcu58hb1mmj3kr6ny9:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "9663676416"
                codePath: student/ablation_studies/tuning_learning_rate.py
                codePathLocal: tuning_learning_rate.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "795302256640"
                email: nd3032@nyu.edu
                executable: /Users/nilarnabdebnath/Documents/course_work/sem2/llm_reasoners/assignment1/nyu-llm-reasoners-a1/.venv/bin/python
                git:
                    commit: 2301b5a5e646500b29a8f4644c2e85602efcc6da
                    remote: https://github.com/nilarnab/nyu-llm-reasoners-a1.git
                host: Nilarnabs-MacBook-Air.local
                memory:
                    total: "25769803776"
                os: macOS-15.7.3-arm64-arm-64bit-Mach-O
                program: /Users/nilarnabdebnath/Documents/course_work/sem2/llm_reasoners/assignment1/nyu-llm-reasoners-a1/student/ablation_studies/tuning_learning_rate.py
                python: CPython 3.13.7
                root: /Users/nilarnabdebnath/Documents/course_work/sem2/llm_reasoners/assignment1/nyu-llm-reasoners-a1/student/ablation_studies
                startedAt: "2026-02-11T02:35:26.955509Z"
                writerId: fg9r5h7jq7ip5ewcu58hb1mmj3kr6ny9
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.13.7
            "5": 0.24.2
            "12": 0.24.2
            "13": darwin-arm64
batch_size:
    value: 64
epochs:
    value: 20000
learning_rate:
    value: 0.001
model:
    value: transformer
